In [1]:
import pandas as pd

In [9]:
d0='../../d0.gz'
d0=pd.read_table(d0,header=None)

In [10]:
d0

,0,1,2,3,4,5,6,7,8,9
0,chr1,100037588,100037685,Peak_287773,295,.,2.77280,29.53313,27.62044,48
1,chr1,100037758,100039236,Peak_17174,1000,.,14.49089,663.87006,660.49304,370
2,chr1,100037758,100039236,Peak_201713,585,.,3.70911,58.58798,56.50302,47
3,chr1,100037758,100039236,Peak_30996,1000,.,11.79564,482.53482,479.48959,261
4,chr1,100037758,100039236,Peak_67122,1000,.,8.12957,263.06052,260.41461,1006
...,...,...,...,...,...,...,...,...,...,...
286551,chrY,7818872,7819262,Peak_218191,508,.,8.42284,50.86534,48.81796,282
286552,chrY,7834390,7834592,Peak_252066,386,.,7.13464,38.65566,36.67830,77
286553,chrY,7874153,7874558,Peak_76812,1000,.,22.89031,229.73851,227.16151,160
286554,chrY,7935944,7936401,Peak_87908,1000,.,20.61119,197.91411,195.40685,288
286555,chrY,7935944,7936401,Peak_88995,1000,.,20.41301,195.19717,192.69611,365